console:
  username: "admin"
  password: "free-ran-ue"

  port: 40104

  jwt:
    secret: "free-ran-ue"
    expiresIn: 1h # 1 hour

  frontendFilePath: "console"

logger:
  level: "info" # error, warn, info, debug, trace, test