gnb:
  amfN2Ip: "10.0.1.3"
  ranN2Ip: "10.0.1.4"
  upfN3Ip: "10.0.1.5"
  ranN3Ip: "10.0.1.4"

  ranControlPlaneIp: "10.0.3.3"
  ranDataPlaneIp: "10.0.3.3"

  amfN2Port: 38412
  ranN2Port: 38413
  upfN3Port: 2152
  ranN3Port: 2152

  ranControlPlanePort: 31413
  ranDataPlanePort: 31414

  gnbId: "314314"
  gnbName: "gNB-secondary"

  plmnId:
    mcc: "208"
    mnc: "93"

  tai:
    tac: "000001"
    broadcastPlmnId:
      mcc: "208"
      mnc: "93"

  snssai:
    sst: "1"
    sd: "010203"

  staticNrdc: true

  xnInterface:
    enable: true
    xnListenIp: "10.0.1.4"
    xnListenPort: 31415
    xnDialIp: "10.0.1.2"
    xnDialPort: 31415

  api:
    ip: "10.0.1.4"
    port: 40104

logger:
  level: "info" # error, warn, info, debug, trace, test